### ISSUE TITLE
To modularize

### ISSUE THREAD

**Issue by suntong** [metatexx/go-app-todo#1]
Can this function,

https://github.com/metatexx/go-app-todo/blob/fa31d5c2b4dafb0cbf116ee03e9cb8a03415ef58/frontend/todos.go#L84-L86

somehow be modularized as a member function like the following please?

https://github.com/metatexx/go-app-todo/blob/fa31d5c2b4dafb0cbf116ee03e9cb8a03415ef58/frontend/todos.go#L61

I want to modularize all functions in UI definitions, but don't know how to deal with extra variables like `i` in above case. Thanks.

**Comment by oderwat** [comment]
I do not understand what you mean with "modularise" the function? You could expose the handler as "c.OnChangeHandler(int)" and call that instead using the same closure to capture the `i`. 

```go
 OnChange(func(ctx app.Context, e app.Event) { 
 	c.OnChangeHandler(i)
 }),
```

You could also give some other parameter to the handler, like the todo entry itself.

**Comment by suntong** [comment]
Ha, sure, I was thinking to replace `func (ctx...` altogether with a single function, but that works as well. Thanks!

**Comment by oderwat** [comment]
To replace the full function, you would use a function factory that gets the `i` and creates an `app.EventHandler` that includes the `i` in a closure. We do this quite a lot because then you have a nicer layout of the code.

**Comment by suntong** [comment]
> We do this quite a lot because then you have a nicer layout of the code.

Yeah, that's what I was hoping to achieve. Would it be too much trouble to show us how you are able to do it please?
