### ISSUE TITLE
error running app

### ISSUE THREAD

**Issue by mgazzin** [metatexx/go-app-todo#2]
Hi @oderwat ,

interesting example. I hope I can learn more on go-app studying this source code!
I have just tried to build and run but I am getting the following error:

![immagine](https://github.com/metatexx/go-app-todo/assets/7835130/33bffb83-59a3-4eb8-b906-d8c821b8be68)

Do you have an idea why I am getting this?

**Comment by oderwat** [comment]
You need to update the packages in the go mod file. Because the go-app release is dependent on the go compiler used.

**Comment by oderwat** [comment]
I updated the packages

`go run mage.go run` should work now.

**Comment by mgazzin** [comment]
Hi @oderwat , are you sure you pushed your update? I do not see any change.

**Comment by oderwat** [comment]
Yes, but no :) I forgot that I have multiple remotes.

**Comment by mgazzin** [comment]
It is ok now. Thanks @oderwat !
